## Pokemon Party

In [19]:
import pandas as pd
import re
pd.options.display.max_rows = 300

In [21]:
pokemon = pd.read_csv('Pokemon_Party.txt', delimiter = '|')
pokemon['IVs'] = pokemon['IVs'].map(lambda x: float(x.strip(' IV%')))
pokemon['Level'] = pokemon['Level'].map(lambda x: int(x.strip('Level ')))

In [22]:
pokemon.head()

     Pokemon     Number  Level    IVs
0  Prinplup    No. - 1      19  60.22
1  Whiscash    No. - 2      54  41.40
2    Starly    No. - 3      39  45.16
3   Venonat    No. - 4      32  26.88
4   Blissey    No. - 5      58  30.11

In [25]:
pokemon.sort_values('Level')

        Pokemon      Number  Level    IVs
59   Porygon-z    No. - 60       2  31.72
33    Lunatone    No. - 34       4  31.72
21   Sandshrew    No. - 22       4  50.00
35   Araquanid    No. - 36       4  45.70
10     Glameow    No. - 11       4  49.46
44     Mantyke    No. - 45       9  48.39
56    Qwilfish    No. - 57       9  52.69
34     Togetic    No. - 35      10  54.84
12      Minior    No. - 13      11  21.51
28    Delcatty    No. - 29      11  34.95
14     Herdier    No. - 16      12  43.01
20       Aipom    No. - 21      12  37.10
17     Golduck    No. - 18      13  58.60
45   Toucannon    No. - 46      14  47.31
25    Archeops    No. - 26      14  38.17
64  Weepinbell    No. - 65      15  36.56
29  Barbaracle    No. - 31      16  58.60
53       Shinx    No. - 54      16  51.08
5       Furret     No. - 6      18  57.53
42     Dugtrio    No. - 43      18  53.23
23  Butterfree    No. - 24      19  39.25
0     Prinplup     No. - 1      19  60.22
51       Aipom    No. - 52      21  43.55
41    Musharna    No. - 42      21  40.32
37   Growlithe    No. - 38      24  32.26
9    Clauncher    No. - 10      25  54.84
49     Pansear    No. - 50      25  29.03
32  Ferrothorn    No. - 33      26  58.06
8      Taillow     No. - 9      27  51.08
40      Horsea    No. - 41      27  34.41
57    Dragalge    No. - 58      28  19.89
60     Nuzleaf    No. - 61      28  32.80
46      Swanna    No. - 47      29  36.56
3      Venonat     No. - 4      32  26.88
48   Vanilluxe    No. - 49      32  45.16
61     Mantyke    No. - 62      32  45.16
58    Skuntank    No. - 59      33  47.31
65      Flygon    No. - 66      33  46.77
13    Raticate    No. - 14      33  50.54
63         Muk    No. - 64      34  59.14
16     Solrock    No. - 17      36  42.47
6    Bounsweet     No. - 7      36  30.65
15  Misdreavus    No. - 15      36  58.60
26      Spoink    No. - 27      37  48.39
39      Klefki    No. - 40      38  29.57
19  Electabuzz    No. - 20      38  48.39
62       Burmy    No. - 63      39  29.03
2       Starly     No. - 3      39  45.16
7      Bruxish     No. - 8      41  40.32
11     Whismur    No. - 12      42  43.55
66       Doduo    No. - 67      43  61.83
47   Spiritomb    No. - 48      43  47.85
36     Lanturn    No. - 37      45  41.94
50   Shiinotic    No. - 51      45  27.96
27      Gastly    No. - 28      46  38.71
30      Wimpod    No. - 30      50  37.10
22     Petilil    No. - 23      53  43.55
1     Whiscash     No. - 2      54  41.40
54    Beedrill    No. - 55      55  30.65
43   Ninetales    No. - 44      55  50.54
31     Haunter    No. - 32      56  47.85
55   Palpitoad    No. - 56      57  58.06
38     Psyduck    No. - 39      57  55.91
24   Clauncher    No. - 25      57  22.04
4      Blissey     No. - 5      58  30.11
18   Shiinotic    No. - 19      59  36.56
52  Whimsicott    No. - 53      60  29.03